/**
 * Datos de ejemplo para desarrollo
 * En producción, estos datos vendrán del backend
 */

import type { Material, LoteProduccion } from "@/types"

export const mockMateriales: Material[] = [
  {
    id: "1",
    codigo: "MAL-PIL-001",
    nombre: "Malta Pilsen",
    categoria: "Maltas",
    stock: 450,
    unidad: "kg",
    stockMinimo: 100,
    proveedor: "Maltería Pampa",
    estado: "Exceso",
    costoUnitario: 850,
    ultimaActualizacion: "2025-10-05T10:30:00Z",
  },
  {
    id: "2",
    codigo: "MAL-MUN-002",
    nombre: "Malta Munich",
    categoria: "Maltas",
    stock: 180,
    unidad: "kg",
    stockMinimo: 80,
    proveedor: "Maltería Pampa",
    estado: "Bueno",
    costoUnitario: 920,
    ultimaActualizacion: "2025-10-06T14:20:00Z",
  },
  {
    id: "3",
    codigo: "MAL-CAR-003",
    nombre: "Malta Caramelo 60L",
    categoria: "Maltas",
    stock: 95,
    unidad: "kg",
    stockMinimo: 50,
    proveedor: "Maltería Pampa",
    estado: "Bueno",
    costoUnitario: 1050,
    ultimaActualizacion: "2025-10-04T09:15:00Z",
  },
  {
    id: "4",
    codigo: "MAL-CHO-004",
    nombre: "Malta Chocolate",
    categoria: "Maltas",
    stock: 35,
    unidad: "kg",
    stockMinimo: 25,
    proveedor: "Maltería Pampa",
    estado: "Bueno",
    costoUnitario: 1150,
    ultimaActualizacion: "2025-10-07T11:45:00Z",
  },
  {
    id: "5",
    codigo: "LUP-CAS-001",
    nombre: "Lúpulo Cascade",
    categoria: "Lúpulos",
    stock: 8.5,
    unidad: "kg",
    stockMinimo: 5,
    proveedor: "Hop Suppliers SA",
    estado: "Bueno",
    costoUnitario: 4500,
    ultimaActualizacion: "2025-10-03T16:00:00Z",
  },
  {
    id: "6",
    codigo: "LUP-CIT-002",
    nombre: "Lúpulo Citra",
    categoria: "Lúpulos",
    stock: 3.2,
    unidad: "kg",
    stockMinimo: 5,
    proveedor: "Hop Suppliers SA",
    estado: "Bajo",
    costoUnitario: 5200,
    ultimaActualizacion: "2025-10-08T08:30:00Z",
  },
  {
    id: "7",
    codigo: "LUP-MOS-003",
    nombre: "Lúpulo Mosaic",
    categoria: "Lúpulos",
    stock: 12.8,
    unidad: "kg",
    stockMinimo: 5,
    proveedor: "Hop Suppliers SA",
    estado: "Bueno",
    costoUnitario: 5500,
    ultimaActualizacion: "2025-10-02T13:20:00Z",
  },
  {
    id: "8",
    codigo: "LUP-SAA-004",
    nombre: "Lúpulo Saaz",
    categoria: "Lúpulos",
    stock: 6.5,
    unidad: "kg",
    stockMinimo: 4,
    proveedor: "Hop Suppliers SA",
    estado: "Bueno",
    costoUnitario: 4800,
    ultimaActualizacion: "2025-10-01T10:00:00Z",
  },
  {
    id: "9",
    codigo: "LEV-US05-001",
    nombre: "Levadura US-05 (Ale Americana)",
    categoria: "Levaduras",
    stock: 15,
    unidad: "sobres",
    stockMinimo: 10,
    proveedor: "Fermentis Argentina",
    estado: "Bueno",
    costoUnitario: 650,
    ultimaActualizacion: "2025-10-09T07:45:00Z",
  },
  {
    id: "10",
    codigo: "LEV-S04-002",
    nombre: "Levadura S-04 (Ale Inglesa)",
    categoria: "Levaduras",
    stock: 8,
    unidad: "sobres",
    stockMinimo: 10,
    proveedor: "Fermentis Argentina",
    estado: "Bajo",
    costoUnitario: 650,
    ultimaActualizacion: "2025-10-08T15:30:00Z",
  },
  {
    id: "11",
    codigo: "LEV-BE256-003",
    nombre: "Levadura BE-256 (Sin Alcohol)",
    categoria: "Levaduras",
    stock: 4,
    unidad: "sobres",
    stockMinimo: 8,
    proveedor: "Fermentis Argentina",
    estado: "Bajo",
    costoUnitario: 720,
    ultimaActualizacion: "2025-10-07T12:00:00Z",
  },
]

export const mockLotes: LoteProduccion[] = [
  {
    id: "1",
    codigo: "LOTE-001",
    ordenProduccionId: "OP-2025-001",
    nombreProducto: "IPA Americana",
    tipoProducto: "IPA Americana - 485L",
    volumenObjetivo: 485,
    volumenReal: 478,
    estado: "Fermentación",
    etapaActual: "Fermentación",
    progreso: 64,
    fechaInicio: "2025-09-14T08:00:00Z",
    fechaFinEstimada: "2025-10-05T18:00:00Z",
    responsable: "Juan Pérez",
    temperatura: 18.5,
    ph: 4.2,
    alertas: [],
    materiales: [
      { materialId: "1", nombreMaterial: "Malta Pilsen", cantidadPlanificada: 95, cantidadUsada: 95, unidad: "kg" },
      { materialId: "5", nombreMaterial: "Lúpulo Cascade", cantidadPlanificada: 2.5, cantidadUsada: 2.5, unidad: "kg" },
      { materialId: "9", nombreMaterial: "Levadura US-05", cantidadPlanificada: 3, cantidadUsada: 3, unidad: "sobres" },
    ],
  },
  {
    id: "2",
    codigo: "LOTE-002",
    ordenProduccionId: "OP-2025-004",
    nombreProducto: "IPA Americana",
    tipoProducto: "IPA Americana - 500L",
    volumenObjetivo: 500,
    volumenReal: 495,
    estado: "En Producción",
    etapaActual: "Cocción",
    progreso: 38,
    fechaInicio: "2025-09-30T10:00:00Z",
    fechaFinEstimada: "2025-10-21T16:00:00Z",
    responsable: "Juan Pérez",
    temperatura: 100,
    ph: 5.3,
    alertas: ["Temperatura elevada"],
    materiales: [
      { materialId: "1", nombreMaterial: "Malta Pilsen", cantidadPlanificada: 98, cantidadUsada: 98, unidad: "kg" },
      { materialId: "6", nombreMaterial: "Lúpulo Citra", cantidadPlanificada: 2.8, cantidadUsada: 2.8, unidad: "kg" },
    ],
  },
  {
    id: "3",
    codigo: "LOTE-003",
    ordenProduccionId: "OP-2025-005",
    nombreProducto: "Lager Clásica",
    tipoProducto: "Lager Clásica - 495L",
    volumenObjetivo: 495,
    volumenReal: 490,
    estado: "En Producción",
    etapaActual: "Maduración",
    progreso: 40,
    fechaInicio: "2025-09-19T09:00:00Z",
    fechaFinEstimada: "2025-10-24T17:00:00Z",
    responsable: "María González",
    temperatura: 2.5,
    ph: 4.3,
    alertas: [],
    materiales: [
      { materialId: "1", nombreMaterial: "Malta Pilsen", cantidadPlanificada: 92, cantidadUsada: 92, unidad: "kg" },
      { materialId: "8", nombreMaterial: "Lúpulo Saaz", cantidadPlanificada: 1.8, cantidadUsada: 1.8, unidad: "kg" },
    ],
  },
  {
    id: "4",
    codigo: "LOTE-004",
    ordenProduccionId: "OP-2025-003",
    nombreProducto: "Stout Imperial",
    tipoProducto: "Stout Imperial - 420L",
    volumenObjetivo: 420,
    volumenReal: 415,
    estado: "En Producción",
    etapaActual: "Fermentación",
    progreso: 55,
    fechaInicio: "2025-09-22T11:00:00Z",
    fechaFinEstimada: "2025-10-18T15:00:00Z",
    responsable: "Carlos Rodríguez",
    temperatura: 19.5,
    ph: 4.1,
    alertas: [],
    materiales: [
      { materialId: "1", nombreMaterial: "Malta Pilsen", cantidadPlanificada: 75, cantidadUsada: 75, unidad: "kg" },
      { materialId: "4", nombreMaterial: "Malta Chocolate", cantidadPlanificada: 12, cantidadUsada: 12, unidad: "kg" },
    ],
  },
  {
    id: "5",
    codigo: "LOTE-005",
    ordenProduccionId: "OP-2025-002",
    nombreProducto: "Pale Ale",
    tipoProducto: "Pale Ale - 350L",
    volumenObjetivo: 350,
    volumenReal: 348,
    estado: "En Producción",
    etapaActual: "Preparación",
    progreso: 15,
    fechaInicio: "2025-10-07T08:30:00Z",
    fechaFinEstimada: "2025-10-28T14:00:00Z",
    responsable: "Ana Martínez",
    temperatura: 22,
    ph: 5.5,
    alertas: [],
    materiales: [
      { materialId: "1", nombreMaterial: "Malta Pilsen", cantidadPlanificada: 65, cantidadUsada: 0, unidad: "kg" },
      { materialId: "5", nombreMaterial: "Lúpulo Cascade", cantidadPlanificada: 1.5, cantidadUsada: 0, unidad: "kg" },
    ],
  },
]
